### ISSUE TITLE
Some questions about soft_string.py

### ISSUE THREAD

**Issue by alwaysuu** [APMonitor/drilling#1]
Hi, it's happy to find the repository about drilling. Actually, I am working on the related filed, stick-slip vibration of drill-string. When I read the soft_string.py, it's difficult for me to understand what these parameters and equations actually mean without specific comments. I may recognize a portion of these variables' meaning based on my own experiences, but I am not sure about that. So I list some in the following.
1. Do ks, js denote stiffness and inertia of one segment, respertively? Same way to kd, jd (does kd mean BHA)?
2. I guess that variable d means angular, not acceleration.
3. Does ds*ks mean damping coefficient?

Hope for your reply! If possible, please leave more comments to make the code understandable. Thank you~

**Comment by APMonitor** [comment]
I added a README.md file to the soft string model repository. There are many other references available but this should be sufficient to explain the variables and equations in this model.

**Comment by alwaysuu** [comment]
Thanks a lot!
